<?php

namespace Tests\AppBundle\Controller;

use AppBundle\Tests\WebTestRefreshDatabaseTrait;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    use WebTestRefreshDatabaseTrait;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        self::runCommand('doctrine:fixtures:load --purge-with-truncate -n --env=test');
    }

    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/');

        $this->assertEquals(200, $client->getResponse()->getStatusCode());
        $this->assertContains('Welcome to Ositel sf3 test', $crawler->filter('.container h1')->text());
    }
}
